---
- name: Install packages
  ansible.builtin.include_tasks: 
    file: packages.yaml

- name: Ensure firewalld is running
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

- name: Set up Firewall for Kubernetes
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  notify: firewall-cmd-reload
  loop:
    - 6443
    - 10250

- name: Copy configuration files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
  loop:
    - etc/modules-load.d/k8s.conf
    - etc/sysctl.d/k8s.conf

- name: Add the dummy module and make sure it is loaded after reboots
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  loop:
    - br_netfilter
    - overlay

- name: Reload systectl
  ansible.builtin.shell:
    cmd: sysctl --system

- name: Enable and start {{ container_runtime }} service
  ansible.builtin.systemd:
    name: "{{ container_runtime }}"
    daemon_reload: yes
    state: started
    enabled: yes

- name: Pull needed system container images for Kubernetes
  ansible.builtin.shell:
    cmd: kubeadm config images pull

- name: Enable and start kubernetes kubelet service
  ansible.builtin.systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes

- name: Initialize the Kubernetes cluster
  ansible.builtin.shell:
    cmd: kubeadm init --pod-network-cidr=10.244.0.0/16
  ignore_errors: true

- name: Create the .kube directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy kubeconfig to {{ ansible_user }}'s home directory
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: true

# - name: Taint node {{ ansible_host }} as master node
#   kubernetes.core.k8s_taint:
#     state: present
#     name: "{{ ansible_host }}"
#     taints:
#       - key: node-role.kubernetes.io/master
#         effect: PreferNoSchedule

- name: Download Flannel YAML
  get_url:
    url: 'https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml'
    dest: '/tmp/kube-flannel.yml'

- name: Install Flannel (Layer 3 Network Fabric for Kubernetes)
  kubernetes.core.k8s:
    state: present
    src: '/tmp/kube-flannel.yml'

# - name: Set up nfs storage class
#   include_tasks: nfs.yaml
#   when: dedicated_nfs
