---

- name: Initialize the Kubernetes cluster
  ansible.builtin.shell:
    cmd: kubeadm init --pod-network-cidr=10.244.0.0/16
  ignore_errors: true

- name: Create the .kube directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy kubeconfig to {{ ansible_user }}'s home directory
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: true

# - name: Taint node {{ ansible_host }} as master node
#   kubernetes.core.k8s_taint:
#     state: present
#     name: "{{ ansible_host }}"
#     taints:
#       - key: node-role.kubernetes.io/master
#         effect: PreferNoSchedule

- name: Download Flannel YAML
  ansible.builtin.get_url:
    url: 'https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml'
    dest: '/tmp/kube-flannel.yml'
    mode: '0644'

- name: Install Flannel (Layer 3 Network Fabric for Kubernetes)
  kubernetes.core.k8s:
    state: present
    src: '/tmp/kube-flannel.yml'

- name: Get the join command
  ansible.builtin.shell:
    cmd: kubeadm token create --print-join-command
  register: join_command

- name: Set join_command as a fact so it is available in worker tasks
  ansible.builtin.set_fact:
    join_command: "{{ join_command.stdout_lines[0] }}"
    cacheable: true
  delegate_to: localhost
  run_once: true
  when: join_command is defined

- name: Get KUBECONFIG
  ansible.builtin.shell:
    cmd: cat "/home/{{ ansible_user }}/.kube/config"
  register: kubeconfig
  become: true

- name: Set kubeconfig as a fact so it is available in worker tasks
  ansible.builtin.set_fact:
    kubeconfig: "{{ kubeconfig.stdout }}"
    cacheable: true
  delegate_to: localhost
  run_once: true
  when: kubeconfig is defined
